USE [master]
GO

/****** Object:  Database [POS]    Script Date: 11/8/2022 7:48:25 AM ******/
CREATE DATABASE [POS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'POS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\POS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'POS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\POS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [POS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [POS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [POS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [POS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [POS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [POS] SET ARITHABORT OFF 
GO

ALTER DATABASE [POS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [POS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [POS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [POS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [POS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [POS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [POS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [POS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [POS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [POS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [POS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [POS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [POS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [POS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [POS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [POS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [POS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [POS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [POS] SET  MULTI_USER 
GO

ALTER DATABASE [POS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [POS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [POS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [POS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [POS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [POS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [POS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [POS] SET  READ_WRITE 
GO


